//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSistemaestudiantes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int id_notas { get; set; }
        public int id_estudiante { get; set; }
        public int id_materia { get; set; }
        public Nullable<int> nota1 { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual materia materia { get; set; }
    }
}
