//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSistemaestudiantes.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notasEstudiantesEntities : DbContext
    {
        public notasEstudiantesEntities()
            : base("name=notasEstudiantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<nota> notas { get; set; }
    }
}
